import {
	IconBrandAstro,
	IconBrandAws,
	IconBrandBootstrap,
	IconBrandCss3,
	IconBrandFigma,
	IconBrandFirebase,
	IconBrandGit,
	IconBrandGithub,
	IconBrandGraphql,
	IconBrandHtml5,
	IconBrandJavascript,
	IconBrandMongodb,
	IconBrandMysql,
	IconBrandNextjs,
	IconBrandNodejs,
	IconBrandPython,
	IconBrandReact,
	IconBrandReactNative,
	IconBrandRedux,
	IconBrandSass,
	IconBrandSwift,
	IconBrandTailwind,
	IconBrandTypescript,
} from "@tabler/icons-react";
import { svg } from "../../../assets";

const { Express, Java, Strapi, MaterialUI } = svg;

export const skills = [
	IconBrandHtml5,
	IconBrandCss3,
	IconBrandJavascript,
	IconBrandTypescript,
	IconBrandNodejs,
	IconBrandPython,
	Java,
	IconBrandSwift,
	IconBrandReact,
	IconBrandNextjs,
	Express,
	IconBrandRedux,
	IconBrandReactNative,
	IconBrandAstro,
	IconBrandTailwind,
	IconBrandBootstrap,
	IconBrandAws,
	IconBrandFirebase,
	IconBrandGraphql,
	IconBrandSass,
	IconBrandFigma,
	IconBrandGit,
	IconBrandGithub,
	IconBrandMongodb,
	IconBrandMysql,
	Strapi,
	MaterialUI
];